Messages:
  noPermission: "&b[&cHalloween&b] &eNo tienes permiso para hacer eso."
  notEnoughArgs: "&b[&cHalloween&b] &eNo has especificado suficientes argumentos."
  undefinedHead: "&b[&cHalloween&b] &eLa cabeza %head% no existe."
  noReward: "&b[&cHalloween&b] &eEste espíritu no tenía regalos."
  wrongHeadLocation: "&b[&cHalloween&b] &eEse catalizador no se puede colocar ahí."
  headPlaced: "&b[&cHalloween&b] &e%player% ha colocado un %bossHead_playername% &e%current_heads_placed%/%max%."
  bossSpawning: "&b[&cHalloween&b] &eTodos los catalizadores han sido colocados, el ser divine despierta."
  bossSpawned: "&b[&cHalloween&b] &e%boss% ha aparecido para repartir miedo y desesperación."
  lowRodTitle: "&c&l¡CUIDADO!"
  lowRodSubtitle: "&aTu caña tiene menos de 10 usos"
  cannotUseBow: "&b[&cHalloween&b] &eNo puedes usar el &5&lDestructor de almas &eaquí."
  bowBroken: "&b[&cHalloween&b] &eTu &5&lDestructor de almas &ese ha roto."
  lowBowUses: "&c&l&nUsos restantes:&e&l %uses%"
  doubleDrop: "&b[&cHalloween&b] &eHas conseguido una doble recompensa."
  rodArguments: "&b[&cHalloween&b] &eEl uso es /lasthunters rod <Probabilidad> [Jugador]"
  bowArguments: "&b[&cHalloween&b] &eEl uso es /lasthunters bow <Usos> [Jugador]"
  destroyerArguments: "&b[&cHalloween&b] &eEl uso es /lasthunters destroyer <Usos> [Jugador]"
  catalystArguments: "&b[&cHalloween&b] &eEl uso es /lasthunters catalyst <Catalizador> [Jugador]"
  fishChanceArguments: "&b[&cHalloween&b] &eEl uso es /lasthunters fishChance <Probabilidad>"
  doubleChanceArguments: "&b[&cHalloween&b] &eEl uso es /lasthunters doubleChance <Probabilidad>"
  addRewardArguments: "&b[&cHalloween&b] &eEl uso es /lasthunters addReward <Rareza> <Identificador>"
  addedFishChance: "&b[&cHalloween&b] &eAñadida probabilidad extra al objeto."
  addedDoubleChance: "&b[&cHalloween&b] &eAñadida probabilidad de doble al objeto."
  addedReward: "&b[&cHalloween&b] &eAñadida recompensa a la rareza %rarity%."
  reload: "&b[&cHalloween&b] &ePlugin recargado con éxito."
  inventoryFullTitle: "&c&l¡Inventario lleno!"
  cannotUseDestroyer: "&b[&cHalloween&b] &eNo puedes usar el &5&lSegador de almas &eaquí."
  destroyerBroken: "&b[&cHalloween&b] &eTu &5&lSegador de almas &ese ha roto."
  failedCatch:
    - "&cMás suerte la próxima vez."
    - "&c¿Para que quieres coger esa cosa?"
    - "&cEs posible que el espíritu no quiera ser tu amiguito."
    - "&c¿Le has dicho UwU al espíritu para ser su amigo?"
    - "&c¿Qué tal si pruebas a pagarle primero?"
  help:
    - "&d-===- &b[&cHalloween&b] &d-===-"
    - "&b/lasthunters &eMuestra esta página."
    - "&b/lasthunters rod <Probabilidad> [Jugador] &eDa una &6&lCaña Estigia&e."
    - "&b/lasthunters bow <Usos> [Jugador] &eDa un &5&lDestructor de almas&e."
    - "&b/lasthunters destroyer <Usos> [Jugador] &eDa un &5&lSegador de almas&e."
    - "&b/lasthunters catalyst <Catalizado> [Jugador] &eDa un &6&lCatalizador&e."
    - "&b/lasthunters fishChance <Probabilidad> &eAñade probabilidad de pescar."
    - "&b/lasthunters doubleChance <Probabilidad> &eAñade probabilidad de doble recompensa."
    - "&b/lasthunters addReward <Rareza> <Identificador> &eAñade una recompensa a una rareza."
    - "&b/lasthuners reload &eRecarga la configuración del plugin."
    - ""
    - "&eLeyenda: &b<> &eObligatorio  &b[] &eOpcional"
    - "&d-===- &b[&cHalloween&b] &d-===-"

Config:
  poolMobsRespawnTime: 30
  maxRegionMobs: 15
  maxCannonChickens: 10
  maxGolems: 7
  enableChests: true
  enableChickens: true
  refillChestsTime: 900
  catchFailSound: ENTITY_ALLAY_HURT
  titleTime: 2
  chickenCannonFireTime: 1
  chickenCannonSuccessChance: 35
  lowRodUses: 10
  HPIcon: "❤"
  golemSpeed: 1.7
  enabledWorlds:
    - Halloween

Chickens:
  normal:
    name: "&5&lAlma"
    weight: 100
    glow: false
    rewards:
      empty: 2000
      rare: 4020
      epic: 2500
      legendary: 1450
      mythic: 30
  bigPrize:
    name: "&e&lPremio gordo"
    weight: 2
    glow: true
    glowingColor: GREEN
    rewards:
      empty: 1000
      legendary: 6000
      mythic: 2500
      divine: 500

Golems:
  draugr:
    name: "&5Draugr &f- &c%hp%"
    weight: 100
    hp: 3
    entity: DROWNED
    glow: false
    rewards:
      empty: 2000
      rare: 4020
      epic: 2500
      legendary: 1450
      mythic: 30
  banshee:
    name: "&3Banshee &f- &c%hp%"
    weight: 2
    hp: 5
    entity: STRAY
    glow: true
    glowingColor: DARK_AQUA
    rewards:
      empty: 1000
      legendary: 6000
      mythic: 2500
      divine: 500

Items:
  rodChanceLore: "&7Probabilidad extra: &e%rodChance%%"
  doubleChanceLore: "&7Probabilidad de doble: &e%doubleChance%%"
  rod:
    name: "&6&lCaña Estigia"
    lore:
      - "&7"
      - "&7Caña espiritual que puede interactuar con"
      - "&7los espíritus y hacer que sean más amistosos."
  bow:
    name: "&5&lDestructor de almas"
    lore:
      - "&7"
      - "&7Este arco puede erradicar"
      - "&7las almas y obtener premios."
    usesLore: "&7Usos: &e%uses%"
  golemDestroyer:
    material: WOODEN_HOE
    name: "&5&lSegador de almas"
    lore:
      - ""
      - "&7Guadaña con la capacidad de golpear y"
      - "&7castigar a los espíritus malignos."
    usesLore: "&7Usos: &e%uses%"

Boss:
  mob: Wbe
  spawn:
    world: Halloween
    x: -310
    y: -22
    z: 118
  headDisappearSound: BLOCK_RESPAWN_ANCHOR_CHARGE
  bossAppearSound: ENTITY_WITHER_SPAWN

Heads:
  wbe:
    location:
      world: Halloween
      x: -319
      y: -22
      z: 109
    signature:
    name: "&6&lCatalizador de wbecerra"
    lore:
      - "&7"
      - "&7Sirve para canalizar energía divina"
      - "&7hacia el altar para invocar a Dios."
  yuch:
    location:
      world: Halloween
      x: -319
      y: -22
      z: 126
    signature:
    name: "&6&lCatalizador de Yuch135"
    lore:
      - "&7"
      - "&7Sirve para canalizar energía divina"
      - "&7hacia el altar para invocar a Dios."
  magra:
    location:
      world: Halloween
      x: -302
      y: -22
      z: 109
    signature:
    name: "&6&lCatalizador de Fros"
    lore:
      - "&7"
      - "&7Sirve para canalizar energía divina"
      - "&7hacia el altar para invocar a Dios."

Pool:
  vindicator:
    weight: 4895
    entity: VINDICATOR
    catchChance: 20
    name: "&5Alma en Pena"
    rewards:
      empty: 4800
      common: 3000
      uncommon: 2000
      rare: 200
  witch:
    weight: 2900
    entity: WITCH
    catchChance: 17
    name: "&5Moira"
    rewards:
      empty: 4900
      common: 2500
      uncommon: 20
      rare: 500
      epic: 100
  wolf:
    weight: 1500
    entity: WOLF
    catchChance: 14
    name: "&5Cachorro de Cerbero"
    rewards:
      empty: 4900
      uncommon: 2500
      rare: 2000
      epic: 500
      legendary: 100
  glow_squid:
    weight: 600
    entity: GLOW_SQUID
    catchChance: 10
    name: "&5Mini Kraken"
    rewards:
      empty: 4980
      rare: 2500
      epic: 2000
      legendary: 500
      mythic: 20
  silverfish:
    weight: 100
    entity: SILVERFISH
    catchChance: 5
    name: "&5Erinia"
    rewards:
      empty: 500
      epic: 5410
      legendary: 4000
      mythic: 60
      divine: 30
  tadpole:
    weight: 5
    entity: TADPOLE
    catchChance: 1
    name: "&5&lCría de Hidra"
    rewards:
      empty: 5000
      mythic: 3500
      divine: 1500